version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=starwarsapi
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql+psycopg2://root:root@db/starwarsapi
      - FLASK_APP=api/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/var/www/starwarsapi
    depends_on:
      - db
