version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=starwarsapi
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  web:
    build: .
    command: >
      flask create-db &&
      flask run --host 0.0.0.0
    environment:
      - DATABASE_URL=postgresql+psycopg2://root:root@db/starwarsapi
      - FLASK_APP=api/app.py
      - FLASK_ENV=development
    ports:
      - "8000:5000"
    volumes:
      - .:/var/www/starwarsapi
    depends_on:
      - db
  test:
    build: .
    command: bash -c "
      flask create-db
      && python -m unittest discover -s api"
    environment:
      - DATABASE_URL=postgresql+psycopg2://root:root@db/starwarsapi
      - FLASK_APP=api/app.py
      - FLASK_ENV=development
    ports:
      - "8000:5000"
    volumes:
      - .:/var/www/starwarsapi
    depends_on:
      - db
